import { ShieldCheck } from "lucide-react";
import { cn } from "@/lib/utils";

/**
 * WCAG conformance badge.
 *
 * Displays the number of design-system token pairs that pass WCAG 2.1 AA
 * in light and dark themes. Numbers come from the static audit JSON
 * generated by /tmp/audit/wcag_audit.py and committed to /public.
 *
 * If the JSON cannot be loaded, the badge stays silent (no UI noise).
 */
export interface WCAGStats {
  total: number;
  AAA: number;
  AA: number;
  FAIL: number;
}

interface WCAGBadgeProps {
  light: WCAGStats;
  dark: WCAGStats;
  variant?: "compact" | "full";
  className?: string;
}

export function WCAGBadge({ light, dark, variant = "compact", className }: WCAGBadgeProps) {
  const lightOk = light.total - light.FAIL;
  const darkOk = dark.total - dark.FAIL;
  const allPass = light.FAIL === 0 && dark.FAIL === 0;

  if (variant === "compact") {
    return (
      <div
        className={cn(
          "inline-flex items-center gap-2 rounded-full border px-3 py-1 text-xs font-semibold",
          allPass
            ? "border-success/40 bg-success/10 text-success"
            : "border-destructive/40 bg-destructive/10 text-destructive",
          className,
        )}
        role="status"
        aria-label={`WCAG 2.1 AA: ${lightOk + darkOk} of ${light.total + dark.total} token pairs pass`}
      >
        <ShieldCheck className="h-3.5 w-3.5" aria-hidden />
        <span>WCAG 2.1 AA</span>
        <span className="text-foreground/70">·</span>
        <span>
          ☀ {lightOk}/{light.total}
        </span>
        <span className="text-foreground/70">·</span>
        <span>
          ☾ {darkOk}/{dark.total}
        </span>
      </div>
    );
  }

  return (
    <div
      className={cn(
        "rounded-2xl border bg-card p-5",
        allPass ? "border-success/30" : "border-destructive/40",
        className,
      )}
    >
      <div className="flex items-start justify-between gap-3">
        <div>
          <h3 className="text-sm font-semibold text-foreground">Accessibility — WCAG 2.1</h3>
          <p className="text-xs text-foreground/75 mt-0.5">
            Design-system token pairs verified against the WCAG contrast formula.
          </p>
        </div>
        <ShieldCheck className={cn("h-6 w-6", allPass ? "text-success" : "text-destructive")} aria-hidden />
      </div>
      <div className="grid grid-cols-2 gap-4 mt-4">
        <ThemeBlock title="Light theme" stats={light} />
        <ThemeBlock title="Dark theme" stats={dark} />
      </div>
    </div>
  );
}

function ThemeBlock({ title, stats }: { title: string; stats: WCAGStats }) {
  const ok = stats.total - stats.FAIL;
  return (
    <div className="rounded-xl border border-border/60 bg-background/60 p-3">
      <div className="text-xs font-medium text-foreground/80">{title}</div>
      <div className="mt-1.5 flex items-baseline gap-1.5">
        <span className="text-2xl font-bold tabular-nums text-foreground">{ok}</span>
        <span className="text-xs text-foreground/70">/ {stats.total} pass</span>
      </div>
      <div className="mt-2 flex flex-wrap gap-1.5 text-[10px] font-semibold">
        <span className="rounded-full bg-success/15 text-success px-2 py-0.5">AAA {stats.AAA}</span>
        <span className="rounded-full bg-warning/15 text-warning px-2 py-0.5">AA {stats.AA}</span>
        <span
          className={cn(
            "rounded-full px-2 py-0.5",
            stats.FAIL === 0 ? "bg-muted text-foreground/70" : "bg-destructive/15 text-destructive",
          )}
        >
          FAIL {stats.FAIL}
        </span>
      </div>
    </div>
  );
}
